Repository KB-project-14/DanJi-FE, pull requests merged in 2025-08, with the labels that each got.

#65 [Feature/scrum 113] : PIN 페이지 추가
  package-lock.json
  package.json
  src/router/index.ts
  src/views/auth/PaymentPinPage.vue
  src/views/auth/SignUpPage.vue
Labels: FEAT, 혜정

#48 [Feature/scrum 92]: tanstack query settings
  package-lock.json
  package.json
  src/api/api.ts
  src/api/queryClient.ts
  src/constants/QueryKey.ts
  src/main.ts
  src/types/types.ts
Labels: FEAT, 지민

#69 [Feature/scrum 118] : 날짜 표기법 통일
  src/components/common/bottomnav/BottomNavItem.vue
  src/components/common/history/CardHistoryItem.vue
  src/components/common/history/CardHistoryItemList.vue
  src/components/common/modal/TransactionFilterModal.vue
  src/views/wallet/history/CardHistoryPage.vue
Labels: FEAT, 도흔

#79 [Feat] : 마이페이지 백엔드 데이터 연동
  src/composables/queries/member/useGetMember.ts
  src/types/member/memberTypes.ts
  src/views/mypage/MypagePage.vue
Labels: FEAT, 지훈

#86 [Feature/scrum 136] : pay api
  src/api/api.ts
  src/api/auth.ts
  src/composables/badge/useBadgeCollection.ts
  src/composables/queries/local/useGetLocalCurrencies.ts
  src/composables/queries/local/useGetLocals.ts
Labels: FEAT, 지민

#83 [Feature/scrum 116] : 지도 세부 기능 구현
  package-lock.json
  package.json
  src/assets/icons/map-marker.svg
  src/components/map/KaKaoMapContainer.vue
  src/components/map/LocalStoreListModal.vue
  src/components/map/LocalStoreMarker.vue
  src/components/map/MapFilters.vue
  src/mocks/data/localStore.ts
  src/types/types.ts
  src/views/map/MapPage.vue
  tailwind.config.js
Labels: FEAT, 소현

#88 [Feature/scrum 127] : 카드 리스트 함수 재설정
  src/components/common/topbar/SettingHeader.vue
  src/components/wallet/HasCardSection.vue
  src/composables/queries/wallet/deleteWallet.ts
  src/composables/queries/wallet/getWalletList.ts
  src/composables/queries/wallet/getWalletTransaction.ts
  src/router/index.ts
  src/views/wallet/history/CardHistoryPage.vue
  src/views/wallet/history/CardSettingPage.vue
Labels: FIX, 도흔

#93 [Feature/scrum 140] : 충전/환전/환불 API 연동
  src/api/api.ts
  src/components/wallet/exchange/ExchageCard.vue
  src/components/wallet/modal/ExchangCashConfirmModal.vue
  src/components/wallet/modal/ExchangeCardConfirmModal.vue
  src/composables/queries/local/useAddLocalCard.ts
  src/composables/queries/transaction/.gitkeep
  src/composables/queries/transaction/usePostTransfer.ts
  src/composables/queries/wallet/useGetWallet.ts
  src/constants/Transaction.ts
  src/types/local/localTypes.ts
  src/types/transaction/.gitkeep
  src/types/transaction/TransactionType.ts
  src/types/wallet/WalletResponseDtoType.ts
  src/utils/benefit.ts
  src/views/wallet/charge/CardChargePage.vue
  src/views/wallet/exchange/ExchangePage.vue
Labels: FEAT, 소현

#94 [Feature/scrum 125] : 카드 순서 바꾸기 API 연동
  src/composables/queries/wallet/getWalletList.ts
  src/composables/queries/wallet/patchWalletOrder.ts
  src/types/wallet/WalletOrder.ts
  src/views/wallet/change/OrderChangePage.vue
Labels: FEAT, 도흔

#100 [Feature/scrum 141] : pay api 연동
  src/api/api.ts
  src/components/badge/BadgeCollectionContents.vue
  src/components/badge/BadgeCollectionTabs.vue
  src/components/badge/BadgeDetail.vue
  src/components/badge/LocalBadgeCollection.vue
  src/components/badge/SpecialBadgeCollection.vue
  src/components/common/topbar/PayHeader.vue
  src/components/layout/Layout.vue
  src/composables/badge/useBadgeCollection.ts
  src/composables/queries/payment/usePostPayment.ts
  src/router/index.ts
  src/stores/signupStore.ts
  src/types/badge/badgeTypes.ts
  src/types/pay/payTypes.ts
  src/types/types.ts
  src/views/pay/PayCompletePage.vue
  src/views/pay/PayPage.vue
  src/views/pay/PayPinPage.vue
  src/views/qr/QRPage.vue
Labels: FEAT, 지민

#106 [Fix/scrum 150] : 카드 발급 뷰의 소소한 수정
  src/components/wallet/create/CardInfo.vue
  src/components/wallet/exchange/ExchageCard.vue
  src/composables/local/useLocalCurrencyInfo.ts
  src/composables/queries/local/useAddLocalCard.ts
  src/composables/queries/local/useGetLocalCurrencies.ts
  src/composables/queries/local/useGetLocals.ts
  src/constants/BenefitMapper.ts
  src/types/local/localTypes.ts
  src/views/wallet/charge/CardChargePage.vue
  src/views/wallet/create/LocalCardCreateDetailPage.vue
  src/views/wallet/create/LocalCardCreateSelectLocalPage.vue
Labels: STYLE, 소현

#108 [Feature/scrum 154] : 라우터 설정, 전체적인 QA 후 자잘한 UI 수정
  src/components/common/bottomnav/BottomNav.vue
  src/components/common/bottomnav/BottomNavItem.vue
  src/components/common/topbar/Header.vue
  src/components/common/topbar/SettingHeader.vue
  src/components/layout/Layout.vue
  src/components/map/KaKaoMapContainer.vue
  src/components/map/LocalStoreListModal.vue
  src/components/map/MapHeader.vue
  src/router/index.ts
  src/views/map/MapPage.vue
  src/views/wallet/history/CardHistoryPage.vue
  src/views/wallet/history/CardSettingPage.vue
  tailwind.config.js
Labels: STYLE, 소현

#129 [Feature/scrum 165] : pinia 설정 및 연동
  package-lock.json
  package.json
  src/composables/home/useHomeCardList.ts
  src/composables/queries/member/useGetMember.ts
  src/composables/queries/wallet/useGetWalletList.ts
  src/composables/queries/wallet/usePatchWalletOrder.ts
  src/constants/CardBgColors.ts
  src/main.ts
  src/stores/useWalletStore.ts
  src/types/wallet/WalletResponseDtoType.ts
  src/views/wallet/change/OrderChangePage.vue
  src/views/wallet/home/HomePage.vue
  src/views/wallet/home/WalletPage.vue
Labels: FEAT, FIX, 지민, REFACTOR
