Repository KB-project-14/DanJi-FE, pull requests merged in 2025-07, with the labels that each got.

#3 [chore] Jira와 깃허브 연동
  .github/ISSUE_TEMPLATE/issue-form.yml
  .github/workflows/close-jira-issue.yml
  .github/workflows/create-jira-issue.yml
Labels: CHORE, 지민

#4 [CHORE] : gitignore에 .env 추가
  .gitignore
Labels: CHORE, 소현

#15 [Feature/scrum 72] :헤더 UI 구현
  package-lock.json
  src/components/common/topbar/Header.vue
Labels: FEAT, 도흔

#19 [Feature/scrum 72] : Main Header UI 구현
  src/App.vue
  src/assets/images/Danji-Logo-Main.png
  src/assets/styles/reset.css
  src/components/common/topbar/MainHeader.vue
Labels: FEAT, CHORE, 도흔

#31 [Feature] scrum 79 - QR UI
  src/assets/icons/checkbox-activated.svg
  src/assets/icons/checkbox-inactivated.svg
  src/assets/icons/fail.svg
  src/assets/icons/success.svg
  src/assets/styles/reset.css
  src/components/common/modal/CashPayFailModal.vue
  src/components/common/modal/LocalPayFailModal.vue
  src/components/common/topbar/PayHeader.vue
  src/components/layout/Layout.vue
  src/components/pay/PayFail.vue
  src/components/pay/PaySuccess.vue
  src/router/index.ts
  src/types/types.ts
  src/views/pay/PayCompletePage.vue
  src/views/pay/PayPage.vue
  src/views/qr/QRPage.vue
  tailwind.config.js
Labels: FEAT, FIX, STYLE, 지민

#30 [Feature] scrum 28 homepage UI 구현
  package-lock.json
  package.json
  src/components/common/card/NoCard.vue
  src/components/common/card/UserCard.vue
  src/components/wallet/HasCardSection.vue
  src/components/wallet/NoCardSection.vue
  src/components/wallet/TotalWallet.vue
  src/router/index.ts
  src/views/wallet/home/HomePage.vue
Labels: FEAT, STYLE, 도흔

#33 [Feature]scrum-85 카드 순서 변경 UI 구현
  package-lock.json
  package.json
  src/components/common/wallet/WalletItem.vue
  src/router/index.ts
  src/views/wallet/change/OrderChange.vue
Labels: FEAT, FIX, 도흔

#34 [Feature] 마이페이지 ui 구현
  src/assets/icons/profile.svg
  src/assets/icons/right-arrow.svg
  src/router/index.ts
  src/views/mypage/MypagePage.vue
  tailwind.config.js
Labels: FEAT, STYLE, 지민

#39 [Feature] : scrum 81 지역화폐 카드 발급 뷰 구현
  docs/components/local-filter-modal-guide.md
  docs/setting/dev-server-network-guide.md
  src/components/common/modal/LocalFilterModal.vue
  src/main.ts
  src/mocks/data/local.ts
  src/mocks/handlers.ts
  src/router/index.ts
  src/views/wallet/create/.gitkeep
  src/views/wallet/create/LocalCardCreatePage.vue
  vite.config.ts
Labels: DOCS, STYLE, 소현

#37 [Feature] scrum 88 QR 결제 기능 구현
  package-lock.json
  package.json
  src/router/index.ts
  src/views/qr/QRPage.vue
Labels: FEAT, STYLE, 지민

#42 [Feature/scrum 89] : 카드 이용내역 UI 구현
  package-lock.json
  package.json
  src/components/common/history/CardHistoryItem.vue
  src/components/common/history/CardHistoryItemList.vue
  src/components/common/modal/TransactionFilterModal.vue
  src/components/common/topbar/SettingHeader.vue
  src/router/index.ts
  src/views/wallet/history/CardHistoryView.vue
Labels: FEAT, FIX, STYLE, CHORE, 도흔

#46 [Feature/scrum 97] : 카드 설정 UI 구현
  package-lock.json
  src/components/common/modal/CardDeleteModal.vue
  src/router/index.ts
  src/views/wallet/change/OrderChangePage.vue
  src/views/wallet/history/CardHistoryPage.vue
  src/views/wallet/history/CardSettingPage.vue
  src/views/wallet/home/WalletPage.vue
Labels: FEAT, STYLE, 도흔

#49 [Refactor/scrum] : 96 layout refactor
  src/components/common/topbar/PayHeader.vue
  src/components/common/topbar/SettingHeader.vue
  src/components/layout/Layout.vue
  src/types/types.ts
  src/views/pay/PayCompletePage.vue
  src/views/pay/PayPage.vue
Labels: 지민, REFACTOR

#53 [Fix/SCRUM-105] : main UI 수정
  src/components/common/card/UserCard.vue
  src/components/common/tooltip/Tooltip.vue
  src/components/wallet/HasCardSection.vue
  src/components/wallet/TotalWallet.vue
  src/router/index.ts
  src/views/wallet/change/OrderChangePage.vue
  src/views/wallet/history/CardHistoryPage.vue
  src/views/wallet/home/HomePage.vue
  src/views/wallet/home/WalletPage.vue
Labels: FEAT, FIX, STYLE, 도흔

#56 [Feature/scrum 104] : 지도 UI 구현
  env.d.ts
  package-lock.json
  package.json
  src/components/common/chip/DanjiChip.vue
  src/main.ts
  src/router/index.ts
  src/views/map/.gitkeep
  src/views/map/MapPage.vue
Labels: FEAT, 소현

#64 [Feature/scrum 108] : 카드 이용내역 수정된 UI 반영
  src/components/common/history/CardHistoryItemList.vue
  src/components/common/modal/TransactionFilterModal.vue
  src/views/wallet/history/CardHistoryPage.vue
Labels: FEAT, FIX, 도흔

#66 [Feature/scrum 112] : 지역카드 발급 ui 수정 사항 반영
  src/components/common/modal/LocalFilterModal.vue
  src/components/wallet/create/CardBenefitInfo.vue
  src/components/wallet/create/CardInfo.vue
  src/router/index.ts
  src/views/map/MapPage.vue
  src/views/wallet/create/LocalCardCreateDetailPage.vue
  src/views/wallet/create/LocalCardCreatePage.vue
  src/views/wallet/create/LocalCardCreateSelectLocalPage.vue
Labels: FEAT, 소현
